spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id:
    custom:
      tossPayMent:
        widget:
          secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6

